import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

// Enum usage should be based on Prisma's generated enums
// If Role enum is generated by Prisma, use it directly
// Assuming Prisma generates Role enum
// enum Role {
//     ADMIN,
//     PRIVATE_BOARDING_OWNER,
//     STANDARD_USER
// }

const seedData: Prisma.UserCreateManyInput[] = [
    { username: 'admin', password: 'admin123', role: 'ADMIN' },
    { username: 'user1', password: 'user123', role: 'STANDARD_USER' }
];

// Function to seed data for each model
async function seedDataForModels() {
    try {
        // Seed data for users
        await prisma.user.createMany({
            data: seedData,
        });

        // Seed data for other models...
    } catch (error) {
        console.error('Error seeding data:', error);
    } finally {
        // Disconnect Prisma client
        await prisma.$disconnect();
    }
}

// Call seed data function
seedDataForModels();
